#!/usr/bin/env bash
# Bash script that will display information about subdomains.
# Requirements:
# 	Add the subdomain www to your domain, point it to your lb-01 IP
#	(your domain name might be configured with default subdomains,
#	feel free to remove them)
# 	Add the subdomain lb-01 to your domain, point it to your lb-01 IP
# 	Add the subdomain web-01 to your domain, point it to your web-01 IP
# 	Add the subdomain web-02 to your domain, point it to your web-02 IP
# 	Your Bash script must accept 2 arguments:
# 		domain: type: string, what: domain name to audit, mandatory: yes
# 		subdomain: type: string, what: specific subdomain to audit, mandatory: no
domain_info () {
	answer="$2.$1."
	dig "$2.$1" | awk '/'"$answer"'/ {if(NF > 3) print "The subdomain " "'"$2"'" " is a " $4 " record and points to " $5}'
}
if [ -z "$2" ]
then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
else
	domain_info "$1" "$2"
fi
