#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting
# to another page.
# Requirements:
#	The redirection must be a “301 Moved Permanently”
#	You answer file should be a Bash script containing commands to
#	automatically configure a Ubuntu machine to respect above requirements
#	Using what you did with 1-install_nginx_web_server,
#	write 3-redirection so that it
#	configures a brand new Ubuntu machine to the requirements
#	asked in this task
sudo apt update
sudo apt -y install nginx
echo 'Hello World!' > /var/www/html/index.html
new_string="location /redirect_me {\n\t\treturn 301 https://intranet.alxswe.com;\n\t}\n"
sudo sed -i "30i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
