#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)
var=$(hostname)
new_string="\terror_page 404 \/custom_404.html;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/intranet.alxswe.com;"
new_string2="server {\n\tadd_header X-Served-By $var;"

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx restart
