#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

sudo apt-get update
sudo apt-get install -y nginx
sudo apt-get install -y haproxy
sudo sh -c 'echo "
frontend node
	default_backend servers
	bind *:80
	mode http
backend servers
	balance roundrobin
	option forwardfor
	option httpclose
	server 172785-web-01 100.25.151.158:80 check
	server 172785-web-02 34.207.57.64:80 check" >>/etc/haproxy/haproxy.cfg'
sudo service haproxy restart

