#!/usr/bin/env bash
# Configure server with: HAproxy version 1.5 or greater
# Distributes request using roundrobin; sends traffic to servers: web-01 and web-02

sudo apt-get update
sudo apt-get install -y nginx
sudo apt-get install -y haproxy
config="\\\nfrontend node\n\tdefault_backend servers\n\tbind 0.0.0.0:80\n\tmode http\n\nbackend servers\n\tbalance roundrobin\n\toption forwardfor\n\toption httpclose\n\tserver 172785-web-01 100.25.151.158:80 check\n\tserver 172785-web-02 34.207.57.64:80 check"
# Make sure HAproxy can be managed via an init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

sudo apt-get update

# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
# Configure to include roundrobin and two servers
sudo sed -i "\$a $config" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
