#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
location=$(date +"%d-%m-%Y.tar.gz")
mysqldump --user=root -p"$1" --all-databases > backup.sql
tar -cvzf $location backup.sql
