#!/usr/bin/env bash
# Bash (init) script 101-manage_my_process that manages manage_my_process.
# Requirements:
# When passing the argument start: Starts manage_my_process, Creates a file containing its PID in /var/run/my_process.pid, Displays manage_my_process started
# When passing the argument stop: Stops manage_my_process, Deletes the file /var/run/my_process.pid, Displays manage_my_process stopped
# When passing the argument restart, Stops manage_my_process, Deletes the file /var/run/my_process.pid, Starts manage_my_process, Creates a file containing its PID in /var/run/my_process.pid, Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed
filename="/var/run/my_process.pid"
scriptname="manage_my_process"
if [ "$#" == 0 ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
else
	case $1 in 
		"start")
			touch $filename
			./"$scriptname" &
			echo "manage_my_process started"
			echo "$!" > "$filename"
			;;
		"stop")
			echo "manage_my_process stopped"
			kill "$(cat $filename)"
			rm "$filename"
			;;
		"restart")
			echo "manage_my_process restarted"
			kill "$(cat $filename)"
			rm "$filename"
			./"$scriptname" &
			echo "$!" > "$filename"
			;;
		*)
			echo "Usage: manage_my_process {start|stop|restart}"
	esac
fi
