#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
filename="/etc/passwd"
while IFS=':' read -r username password userid groupid useridinfo homedir shell
do
	echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < $filename
