#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes display hours from 0 to 12 display minutes from 1 to 59
for ((hr=0; hr<24; hr++))
do
	echo "Hour $hr"
	for ((min=1; min<60; min++))
	do
		echo "$min"
	done
done
