#!/usr/bin/bash
# install the ufw firewall and setup a few rules on web-01
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 22 (SSH), 443 (HTTPS SSL), 80 (HTTP)
sudo apt-get install ufw
sudo ufw allow http
sudo ufw allow https
sudo ufw allow ssh

