#!/usr/bin/env bash
# get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it.
apt update
apt install apache2
apt install curl
/etc/init.d/apache2 start
echo "Hello Holberton" > /var/www/html/index.html
sed -i "s/Listen 80/Listen 8080/g" /etc/apache2/ports.conf
service apache2 restart
