#!/usr/bin/env bash
# Requirements:
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove
# Write a Bash script that configures the container to fit the above requirements
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
sed -i "s/listen [::]:80/listen [::]:8080/g" /etc/nginx/sites-enabled/default
service nginx restart
