#!/usr/bin/env bash
# application servers are designed with a master/workers infrastructure. The master is in charge of: Receiving requests, Managing workers (starting, stopping), Distributing requests to workers
# Workers are the actual ones processing the query by generation dynamic content by processing the application code.
# To update an application without downtime, the master will proceed with a progressive rollout of the update. It will gracefully shut down some workers ( meaning that it will tell workers to finish processing the request they are working on, but will not send them new requests, once the worker is done, it’s will be shutdown) and start new ones with the new application code or configuration, then move on to the other old workers until it has renewed the whole pool.
# Bash script to reload Gunicorn in a graceful way.
sudo grep gunicorn | xargs kill -MUP
